### ISSUE TITLE
چجوری از ماژولتون استفاده کنم؟

### ISSUE THREAD

**Issue by ehsankhorasani** [a-roomana/django-jalali-date#1]
سلام
من یه مشکلی با مثالی که زدین دارم
و نمیتونم تو پروژه خودم ازش استفاده کنم
این مدل منه
`class Food(models.Model):
   serve_date = models.DateField(verbose_name="Serve Date")
`
میشه بگید که چجوری باید از ماژولتون استفاده کنم؟

**Comment by a-roomana** [comment]
سلام
دوست عزیز این ماژول برای تبدیل خودکار تاریخ در قسمت میدیریت جنگو هستش. در واقع تمام تاریخ های شما به صورت میلادی در دیتابیس ذخیره میشه تنها زمانی که در یک فرم میخوایم اون تاریخ رو نشون بدیم تاریخ ها به صورت خودکار به شمسی تبدیل میشه وبه کاربر نمایش داده میشه و هنگام ذخیره از شمسی به میلادی تبدیل میشه و در دیتابیس ذخیره میشه.

برای این کار نیازی نیست که در کد مدلتون تغییری ایجاد کنید. بلکه باید طبق داکیومنت تنها زمانی که میخواهید که مدل را در آدمین جنگو رجیستر کنید به جای مدل آدمین جنگو, مدل آدمین من رو به ارث ببرید. لطفا یک باری دیگه داکیومنت رو نگاه کنید.

**Comment by meysol** [comment]
با سلام وقتتون بخیر. چطور میشه تاریخ رو در فایل ویو به صورت حروف نشون داد
مثلا
سه شنبه 3 آذر 98 
و
9 ماه پیش

**Comment by a-roomana** [comment]
@meysol 
<p dir='rtl'>
با سلام
مطابق با داکیومنت میتوانید همانند کد زیر عمل کنید.
</p>

```python
from jalali_date import datetime2jalali, date2jalali

def my_view(request):
	jalali_join = datetime2jalali(request.user.date_joined).strftime('%a %d %b %y')
        # دوشنبه 27 آبان 98
```

<p dir='rtl'>
برای پیدا کردن فرمت دلخواه خود میتوانید از لینک زیر استفاده کنید
</p>

[strftime.org](http://strftime.org/)

**Comment by mrezaanony** [comment]
سلام 
ببخشید یه سمپل کد جامع برای کار با متد های این ماژول ندارید برای عکسایی که تازه میخوان با پایتون و جنگو کار کنن کار سختیه فهمیدن این ماژول 
اصلا نمیشه فهمید
