### ISSUE TITLE
عدم نمایش تقویم در custom form

### ISSUE THREAD

**Issue by soheilabehyari** [a-roomana/django-jalali-date#11]
سلام
من ازین ماژول استفاده کردم
برای فیلد های مدل نمایش داده میشه
ولی وقتی از ادمین فرم استفاده میکنم و فیلد جدیدی اضافه میکنم اونجا 
تقویم ظاهر نمیشه برای فیلد تاریخم
ممنون میشم راهنمایی کنید

**Comment by a-roomana** [comment]
سلام، میبخشید که با تاخیر جواب میدم.
در حالت عادی آدمین جنگو ما فرمی که ساخته خواهد شد را تغییر  میدهیم، شما اگر میخواهید از یک فرم دلخواه در آدمین جنگو استفاده کنید، باید مطابق با مثال در داکیومنت، فیلدهای تاریخ را شمسی کنید.

**Comment by alikomijani** [comment]
سلام
خارج از محیط جنگو ادمین هم قابل استفاده است؟
اگه ممکنه یه راهنمایی بفرمایید

**Comment by a-roomana** [comment]
سلام، بله

برای این که تبدیل تاریخ در فرم شما نیز به درستی کار کند باید مطابق با داکیومنت فیلد مورد نظر در فرم را به صورت زیر تغییر بدهید.

```python
self.fields['some_field'] = JalaliDateField(widget=AdminJalaliDateWidget)
```

مطابق با داکیومنت اگر شما دو خط زیر را در تمپلیت بعد از لود کردن جیکوئری قرار بدهید، ویجت نمایش تاریخ برای فیلد های که کلاس jalali_date-date رو دارن نمایش داده خواهد شد.

```
<link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
<script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
```

**Comment by MohammadGoodarzi** [comment]
فرمی خارج از ادمین نمیتونه از این استفاده کنه؟ میفرمایید چطور؟

**Comment by a-roomana** [comment]
> سلام، بله
> 
> برای این که تبدیل تاریخ در فرم شما نیز به درستی کار کند باید مطابق با داکیومنت فیلد مورد نظر در فرم را به صورت زیر تغییر بدهید.
> 
> ```python
> self.fields['some_field'] = JalaliDateField(widget=AdminJalaliDateWidget)
> ```
> 
> مطابق با داکیومنت اگر شما دو خط زیر را در تمپلیت بعد از لود کردن جیکوئری قرار بدهید، ویجت نمایش تاریخ برای فیلد های که کلاس jalali_date-date رو دارن نمایش داده خواهد شد.
> 
> ```
> <link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
> <script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
> ```

سلام وقت بخیر
مطابق با کد بالا میتوانید عمل کنید.
