### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Omid888** [a-roomana/django-jalali-date#14]
I installed jalali_date and added 'jalali_date' to settings.py and started the project. (I did nothing else) and got the following error: 

> ModuleNotFoundError: No module named 'jalali_daterequest'

Can you dig into it?
if any more information is needed, I'm available.
python 3.7.3
django 2.2.2

**Comment by a-roomana** [comment]
سلام
فکر میکنم یک سوتی کوچیک دادید. احتمالا تنظیمات شما به این شکل است!
```python
INSTALLED_APPS = [
	'other_apps',
	'jalali_date'
	'request',
]
```

فکر کنم که بعد از وارد کردن `jalali_date` کاما نگذاشتید!!

**Comment by Omid888** [comment]
Sorry, My bad..
