### ISSUE TITLE
نمایش شمسی به جای میلادی

### ISSUE THREAD

**Issue by MOAB7698** [a-roomana/django-jalali-date#16]
خوب حالا اگه بخواهیم تاریخ را ک ثبت شده نمایش بدیم چه کار باید کرد و این که براد تبدید شمسی به میلادی (برای کار با تاریخ چه کار باید کرد

**Comment by a-roomana** [comment]
برای تبدیل تاریخ در فایل ها پایتونی میتونید مطابق با داکیومنت از مثل کد زیر اقدام کنید

```python
from jalali_date import datetime2jalali, date2jalali

def my_view(request):
	jalali_join = datetime2jalali(request.user.date_joined).strftime('%y/%m/%d _ %H:%M:%S')
```
برای تبدیل تاریخ میلادی به شمسی در تمپلیت جنگو میتوانید مطابق با داکیومنت مثل کد زیر عمل کنید:

```
{% load jalali_tags %}

<p>{{ request.user.date_joined|to_jalali:'%y/%m/%d _ %H:%M:%S' }}</p>
```

**Comment by MOAB7698** [comment]
چیزی که من توی دیتابیسم ذخیره می کنم تاریخ به صورت جلالی حال با استفاده از
`from jalali_date import datetime2jalali, date2jalali

def my_view(request):
	jalali_join = datetime2jalali(request.user.date_joined).strftime('%y/%m/%d _ %H:%M:%S')`
تاریخ درس رو بهم برنمی گردونه 
این وقتی کار می کنه که تو دیتا بیش تاریخ به صورت میلادی ذخیره شده باشه

**Comment by MOAB7698** [comment]
`from jalali_date import datetime2jalali, date2jalali

def my_view(request):
jalali_join = datetime2jalali(request.user.date_joined).strftime('%y/%m/%d _ %H:%M:%S')`

**Comment by a-roomana** [comment]
دردیتابیس باید میلادی ذخیره کنید،‌فقط هنگام نمایش در تمپلیت، فرم، پنل آدمین و ... با استفاده از مثال های داکیومنت به شمسی و برعکس تبدیل کنید

**Comment by aminimani35** [comment]
که اینطور ممنون

**Comment by mavenium** [comment]
> دردیتابیس باید میلادی ذخیره کنید،‌فقط هنگام نمایش در تمپلیت، فرم، پنل آدمین و ... با استفاده از مثال های داکیومنت به شمسی و برعکس تبدیل کنید

با سلام، برای تبدیل از جلالی به میلادی متدی در ین کتابخونه هست ؟

**Comment by a-roomana** [comment]
> > دردیتابیس باید میلادی ذخیره کنید،‌فقط هنگام نمایش در تمپلیت، فرم، پنل آدمین و ... با استفاده از مثال های داکیومنت به شمسی و برعکس تبدیل کنید
> 
> با سلام، برای تبدیل از جلالی به میلادی متدی در ین کتابخونه هست ؟

در این لایبرری برای تبدیل تاریخ از شمسی به میلادی یا برعکس از کتابخانه jdatetime استفاده شده است.

**Comment by vahidnadi** [comment]
با روش شما تنظیمات رو انجام دادم ولی تقویم به صورت میلادی نماش داده میشه

**Comment by faalkhah** [comment]
ضمن سلام خدمت a-roomana عزیز من این کتابخانه را برای بخش ادمین جنگو لازم دارم. اگر لطف کنید و راهنمایی کنید که منظور از اون سه تا مدل در admin.py چی هست ممنون می شم. منظورم FirstModel , SecendModel و ایناست. فرض کنید من یک مدل بیشتر ندارم چجوری باید تو admin.py درستش کنم.
ضمنا داکیومنت جامعی هم براش پیدا نکردم اگه لینکی هست بفرمایید.
بازم ممنون

**Comment by shabanih** [comment]
سلام
من jalali datePicker  رو در جنگو نصب کردم ولی موقع submit ارور Enter Valid Date  میده. میشه لطفا راهنمایی بفرمایید
