### ISSUE TITLE
مشکل در ذخیره‌ی دیتا در پنل ادمین

### ISSUE THREAD

**Issue by SinaZK** [a-roomana/django-jalali-date#17]
با سلام،
 از ویجت شما استفاده کردم. هنگام تغییر فیلد زمان پیکر شمسی در پنل ادمین نمایش داده میشود. پس از انتخاب تاریخ مورد نظر هنگام سیو مدل در ادمین با فیلد‌هایی که با پیکر شما انتخاب شده‌اند 
ValidationError
میدهند.
خطای نمایش داده شده در ادمین:
Enter a valid date.
نسخه‌ی جنگو:
2.1.5

**Comment by a-roomana** [comment]
سلام وقت بخیر.
آیا شما در پنل ادمین تغییری ایجاد کردید؟ یا لایبرری خاصی رو به کار بردید؟
چرا که احتمالا تغییری ایجاد شده که عدد تاریخ ها فارسی به سمت سرور ارسال میشن.

من باز هم تست کردم، همچین مشکلی دیده نشد. برای این که مشکل شما هم حل بشه، لطفا جاواسکریپت یا هرچیزی که باعث بشه به صورت خودکار اعداد انگلیسی به فارسی تبدیل بشن رو بررسی کنید که ایا در ادمین دارید یا خیر.

**Comment by jsaman19** [comment]
سلام وقت بخیر
این مشکل رو من هم دارم زمانی کاملا مثل مستندات رفتم جلو اما موقع ذخیره خطا میده
جانگو ۳.۰.۸
زمانی که تاریخ و انتخاب نکردم و دیفالت اون لحظه هست توو ریکوئست این شکلی میره
published_at_0 : 1399-05-05
initial-published_at_0 : 2020-07-26

اما زمانی که تاریخ و تغییر میدی جفت این مقادیر شمسی میشه
هرچند در جفت این دو حالت همچنان این مشکل ذخیره نشدن به خاطر نامعتبر بودن تاریخ هست چه انتخاب کنی تغییر بدی تاریخ و چه تغییر ندی و دیفالت اون لحظه باشه
