### ISSUE TITLE
Read only fields

### ISSUE THREAD

**Issue by MJafarMashhadi** [a-roomana/django-jalali-date#2]
Provided mixins and overrides do not seem to be able to affect read only fields. They're still rendered with gregorian date and time values.

**Comment by a-roomana** [comment]
سلام میبخشید نوتیفیکشن رو خاموش کرده بودم یه مقدار دیر مطلع شدم.

بنا به تذکر شما در نسخه جدید، تاریخ های "فقط خواندنی" هم به صورت شمسی نمایش داده میشوند.

اگر مورد دیگری هم هست خوشحال میشم.

**Comment by MJafarMashhadi** [comment]
Thanks for your response. There seems to be a problem with templates in the pip version though.

I checked if `templates` folder is present in the repository and it was, also I checked if the version number had been increased and it was OK too. 

I don't know what is causing this but `templates` folder is missing from the package when installed with `pip`.

**Comment by MJafarMashhadi** [comment]
I decided to use it as a git submodule to keep up with the latest changes, but the version on the PyPi is unstable anyway.

**Comment by a-roomana** [comment]
ممنون از تذکرتون، الان دیگه نباید مشکلی داشته باشه.
