### ISSUE TITLE
نمایش فارسی تاریخ ها در تپملیت -  locale.setlocale

### ISSUE THREAD

**Issue by alishirmohammadi** [a-roomana/django-jalali-date#20]
<p dir="rtl">
وقتی از <code>{{ time|to_jalali:'%B' }}</code> در تمپلیت جنگو استفاده می‌کنم نام ماه به صورت انگلیسی نمایش داده می‌شود. برای نمایش فارسی چه‌کار باید کرد؟
</p>

**Comment by a-roomana** [comment]
برای نمایش فارسی تاریخ ها باید در تنظیمات `environment` را فارسی ست کنید. برای این کار میتوانید از روش های زیر اقدام کنید.

- set the local in uwsgi, gunicorn or DockerFile. for example uwsgi.ini
```
LANG=fa_IR.UTF-8 
LANGUAGE=fa_IR.UTF-8
```

- or set the locale in settings.py
```python
LANGUAGE_CODE = 'fa-ir'
import locale
locale.setlocale(locale.LC_ALL, "fa_IR.UTF-8")
```
- or run server with LC_ALL env
```bash
LC_ALL=fa_IR python manage.py runserver
```

**Comment by vhdm** [comment]
@a-roomana
سلام، ضمن تشکر از زحمات شما  من از جنگو  3 استفاده میکنم، هر کاری کردم ایام هفته ماه ها فارسی بشن، نشد، همه ی این روش ها رو تست کردم.
ممنون میشم راه حلی ارائه بدین

**Comment by farhadmpr** [comment]
> @a-roomana
> 
> سلام، ضمن تشکر از زحمات شما من از جنگو 3 استفاده میکنم، هر کاری کردم ایام هفته ماه ها فارسی بشن، نشد، همه ی این روش ها رو تست کردم. ممنون میشم راه حلی ارائه بدین

Change your language code in settings.py to:
`LANGUAGE_CODE = 'fa'`

**Comment by farhadmpr** [comment]
سلام، من هم همین مشکل را دارم

**Comment by a-roomana** [comment]
@farhadmpr @vhdm @alishirmohammadi 

<p dir="rtl">
برای جنگو ۱ و  احتمالا بعضی از نسخه های ۲ فکر میکنم که باید مطابق با کد زیر عمل کرد.
</p>

```python
LANGUAGE_CODE = 'fa-ir'

import locale
locale.setlocale(locale.LC_ALL, "fa_IR.UTF-8")
```
<p dir="rtl">
اما برای نسخه ۳ فکر میکنم که باید به صورت زیر تغییر داد.من رو جنگو 3.0.1 تست کردم و به درستی کار کرد.
</p>

```python
LANGUAGE_CODE = 'fa'

import locale
locale.setlocale(locale.LC_ALL, "fa_IR.UTF-8")
```

**Comment by therealak12** [comment]
If you're using ubuntu, first install the language pack by:
```bash
sudo apt install language-pack-fa
```
Then use `setlocale` in Django.

**Comment by sam1365** [comment]
می تونید تاریخ رو به میلادی ذخیره کنید و فقط برای نمایش به فارسی از یه تیکه کد جاوااسکریپت استفاده کنید

**Comment by iam-Robo** [comment]
سلام و خسته نباشید
من تمام اینارو که گفتین رو انجام دادم اما  اسم ماه بجای **شهریور** بصورت **Shahrivar** نمایش داده میشه
ممنون میشم اگربتونین کمکم کنین.
تگ رو به اینصورت نوشتم
{{date_now|to_jalali:'%H:%M - %B- %Y/%m/%d'}}

**Comment by iam-Robo** [comment]
> {{ time|to_jalali:'%B' }}



> @a-roomana
> 
> سلام، ضمن تشکر از زحمات شما من از جنگو 3 استفاده میکنم، هر کاری کردم ایام هفته ماه ها فارسی بشن، نشد، همه ی این روش ها رو تست کردم. ممنون میشم راه حلی ارائه بدین

سلام
تونستین این مورد رو حل کنین؟ منم مشکل دارم

**Comment by zoomlordir** [comment]
i dont know why the output is in english in a persian package anyway you guys can use the custom template tags to fix this 
```
from django import template
from jalali_date import date2jalali

register = template.Library()


@register.filter
def jalalidate(value):
    name = date2jalali(value).strftime("%B")
    months = {
        'Esfand': 'اسفند'
    }
    if name in months:
        month = months.get(name)
    date = date2jalali(value).strftime(f"%Y/{month}/%d")
    return date
```
complete the list if you want it im too lazy for that
