### ISSUE TITLE
شمسی ذخیره می‌شود

### ISSUE THREAD

**Issue by iamliji** [a-roomana/django-jalali-date#21]
در دادگان به صورت شمسی ذخیره می‌شود
![Capture](https://user-images.githubusercontent.com/34378752/67641000-9326d000-f913-11e9-9bfa-a15c3d38f9ee.PNG)

**Comment by a-roomana** [comment]
@legee 
سلام
مطمئن هستید که براساس داکیومنت و مثال های موجود کد خود را پیاده سازی کردید؟

شما از طریق فرم جنگو این فیلد را پر کردید یا از طریق دیگری؟

**Comment by legee** [comment]
با سلام و تشکر

views:
```
if form.is_valid():
   BeginDate=form.cleaned_data['BeginDate']
```

Template:
```
</div> {{ form.BeginDate }} </div>
<button type="submit"> Add </button>  
```
Try to convert manualy, return AttributeError:
_err: 'datetime.datetime' object has no attribute 'jyear'_
` BeginDate = JalaliToGregorian(BeginDate.jyear,BeginDate.jmonth,BeginDate.jday)`

**Comment by legee** [comment]
با سلام  
converted manually.

**Comment by a-roomana** [comment]
@legee 
در کدی که سری قبل به من نشون دادید فکر میکنم که چند نکته رو باید بیان کنم

زمانی که شما از  JalaliDateField استفاده میکنید، سمت فرآنت شما تاریخ شمسی وارد میکنید اما به محض این که فرم اعتبارسنجی میشه در واقع 

```python
form.is_valid()
```
صدا زده میشه، تاریخ ها به میلادی تبدیل میشوند و شما اگر مقدار فیلد را بگیرید یک تاریخ میلادی خواهد بود. و زمانی هم که فرم را ذخیره کنید تاریخ میلادی ذخیره خواهد شد نه شمسی.

حال ممکن است که شما بخواهید در فرم یا ویو از مقدار شمسی آن استفاده کنید، طبیعتا باید مقدار میلادی را در یک متغییر دیگر به شمسی تبدیل کنید. دقت کنید که مقدار درون فرم را نباید شمسی کنید.
برای تبدیل تاریخ میلادی به شمسی میتوانید همانند داکیومنت از کد زیر استفاده کنید

```python
from jalali_date import datetime2jalali, date2jalali

jalali_date = datetime2jalali(form.cleaned_data['my_field'])
```

در نهایت فکر میکنم علت این که در دیتابیس تاریخ شمسی ذخیره شده است این است که شما در فرم یا ویو مقدار آن را از به صورت دستی از میلادی به شمسی تبدیل کرده اید

**Comment by ZahraZarei** [comment]
سلام
در قسمت ادمین به صورتی که گفتید اضافه کردم و درست کار میکنه فقط آیکون تقویم رو نشون نمیده. اما در فرمهای خودم که html
هستن، با جاوا اسکریپت مثل راهنما اضافه کردم، نمایش میده اما پس از انتخاب  تاریخ توی فیلد برعکس نشون میده موقع ذخیره هم میگه فرمت تاریخ اشتباهه. 
<input type="text" id="datepicker0"  size="8" maxlength="8" name="birthDate"   required="true" class="form-control">
و در پایین هم
    <script type="text/javascript">
        $(function() {
            $('#datepicker0').datepicker({
                changeMonth: true,
                changeYear: true
            });
            });
    </script>
خطا هنگام ذخیره فرم:
“07/11/1398” value has an invalid date format. It must be in YYYY-MM-DD format.

**Comment by ZahraZarei** [comment]
سلام
من هم همین مشکل رو دارم در فرمهای ادمین به صورت میلادی ذخیره میشود اما در فرمهای خودم به صورت شمسی ذخیره میشود.
    <script type="text/javascript">
        $(function() {
            $('#datepicker0').datepicker({
              dateFormat: 'yy-mm-dd',
              changeMonth: true,
              changeYear: true
            });
            });
    </script>
به صورت فوق در فرم 
html 
 استفاده میکنم.

**Comment by deebajee2009** [comment]
> @legee در کدی که سری قبل به من نشون دادید فکر میکنم که چند نکته رو باید بیان کنم
> 
> زمانی که شما از JalaliDateField استفاده میکنید، سمت فرآنت شما تاریخ شمسی وارد میکنید اما به محض این که فرم اعتبارسنجی میشه در واقع
> 
> ```python
> form.is_valid()
> ```
> 
> صدا زده میشه، تاریخ ها به میلادی تبدیل میشوند و شما اگر مقدار فیلد را بگیرید یک تاریخ میلادی خواهد بود. و زمانی هم که فرم را ذخیره کنید تاریخ میلادی ذخیره خواهد شد نه شمسی.
> 
> حال ممکن است که شما بخواهید در فرم یا ویو از مقدار شمسی آن استفاده کنید، طبیعتا باید مقدار میلادی را در یک متغییر دیگر به شمسی تبدیل کنید. دقت کنید که مقدار درون فرم را نباید شمسی کنید. برای تبدیل تاریخ میلادی به شمسی میتوانید همانند داکیومنت از کد زیر استفاده کنید
> 
> ```python
> from jalali_date import datetime2jalali, date2jalali
> 
> jalali_date = datetime2jalali(form.cleaned_data['my_field'])
> ```
> 
> در نهایت فکر میکنم علت این که در دیتابیس تاریخ شمسی ذخیره شده است این است که شما در فرم یا ویو مقدار آن را از به صورت دستی از میلادی به شمسی تبدیل کرده اید


اگر مقادیر تاریخ که با تابع تبدیل کردیم به شمسی بخواهیم در همون مدل متصل به فرم ذخیره بکنیم باید کار بکنیم؟
