### ISSUE TITLE
تبدیل تاریخ شمسی به میلادی

### ISSUE THREAD

**Issue by MohammadGoodarzi** [a-roomana/django-jalali-date#24]
باسلام
 تبدیل تاریخ شمسی به میلادی چگونه است؟ ممنون

**Comment by a-roomana** [comment]
<div dir='rtl'>
برای تبدیل تاریخ از میلادی به شمسی میتوانید مطابق با داکیومنت از datetime2jalali استفاده کنید. نکته این تابع این است که timezone را هم در نظر میگیرد.

در صورتی که میخواهید تاریخ میلادی به شمسی را تبدیل کنید، ما از لایبرری jdatetime استفاده میکنیم

مطابق با داکیومنت این لایبرری میتوانید به شکل زیر تبدیل زیر را انجام دهید.
</div>

```python
from jdatetime import  datetime as jalali_datetime
jalali_date = jalali_datetime.strptime(your_date_as_str, format_of_date).togregorian()
```

**Comment by MohammadGoodarzi** [comment]
من به عنوان ورودی  تاریخ شمسی رو میدم ولی خطای زیر دیده میشه:
time data '۱۳۹۸/۱۲/۰۶' does not match format '%Y/%m/%d'
