### ISSUE TITLE
not working for extra inlines

### ISSUE THREAD

**Issue by xaoirse** [a-roomana/django-jalali-date#27]
سلام من از آخرین نسخه استفاده میکنم
موقعی که ما این تقویم رو روی یک مدل اعمال میکنیم و بعد اون مدل رو به صورت این لاین میاریم فقط به تعدادی که اول هست اعمال میشه و برای اون این لاین هایی که اضافه میکنیم ویجت نمیاد.
مثلا:
`class Inter_Dep_inline(TabularInlineJalaliMixin,admin.TabularInline):
    model = Inter_Dep
    extra = 2`
فقط برای اون دوتا این لاین که اول هست ویجت اعمال میشه و هرچی که این لاین اضافه بشه برای اونا ویجت نمایش داده نمیشه حتی اگه مثلا به شکل زیر استفاده کنیم
`class Inter_Dep_inline(admin.TabularInline):
    model = Inter_Dep
    extra = 2
    formfield_overrides = {
        models.DateField: {'widget': AdminJalaliDateWidget},
    }`

**Comment by a-roomana** [comment]
<p dir="rtl">بله متاسفانه این مشکل وجود دارد و با عرض پوزش تا اواخر بهمن امکان زمان گذاشتن روی هیچ کاری رو ندارم ( به دلایل کارهای شخصی)</p>

<p dir="rtl">البته علت این مشکل کاملا js هستش اگر شما برای این مورد راه حلی داشتید خوشحال میشم..</p>

**Comment by a-roomana** [comment]
@sanonymoux 
<p dir="rtl">با سلام در نسخه جدید (نسخه 0.3.1) مشکل یاد در جنگو ۳ حل شد.</p>

**Comment by sanonymoux** [comment]
سلام
مشکل نیومدن ویجت حل شده اما یه مشکل داره این که وقتی یه آیتم اضافه میکنید تاریخ براش نمیاد و برای آیتم بعدی که اضافه میکنید اعمال میشه اگه لازمه اسکرین شات بدم؟

**Comment by a-roomana** [comment]
<p dir="rtl">
فکر میکنم که این مورد رو هم تست کردم! درست شده بود! از اون جای که ویجت تاریخ رو شما به درستی مشاهده کردید احتمال کش نیست.
</p>
<p dir="rtl">
حالا شما مطمئن بشید که مشکل کش نیست. من هم امشب دوباره بررسی میکنم.
</p>

**Comment by a-roomana** [comment]
<p dir="rtl">من دوباره تست کردم، همچین موردی مشاهده نشد، فکر میکنم کش شده است.</p>
<p dir="rtl">اضافه کردن سطر جدید با زدن دکمه اضافه کردن</p>

[مشاهده اسکرین شات](http://bayanbox.ir/view/6199620046165808651/Screenshot-from-2020-02-08-23-25-17.png)

**Comment by sanonymoux** [comment]
وقتی یه سطر جدید اضافه میکنید روی اون میزنید و ویجت باز میشه میتونید تاریخ انتخاب کنید که توی تکست باکس بیاد؟

**Comment by a-roomana** [comment]
<p dir="rtl">
بله درست میگید، امان از جاواسکریپت!
</p>
<p dir="rtl">من امروز چند ساعت زمان گذاشتم، حالا خود شما هم یه مقدار بررسی کنید ببینید میشه راه حلی پیدا کنیم.</p>

**Comment by sanonymoux** [comment]
!سعی میکنم ولی متاسفانه تسلط کافی به جاوا اسکریپت ندارم

**Comment by a-roomana** [comment]
@nimasalemahim
<p dir=rtl>
می‌توانید این مشکل را در این ایشو پیگیری کنید، اگر خود شما نیز راه حلی داشته باشید خواشحال خواهم شد و کد شما را تحت یک مرج ریکوئست به کدهای دیگر با نام شما افزوده خواهد شد.
</p>

**Comment by nimasalemahim** [comment]
بله دیدم متشکرم به نظرتون حل میشه یا خیلی کار داره چون من به js تسلط ندارم
که بخوام بررسی کنم

**Comment by a-roomana** [comment]
@nimasalemahim 
> بله دیدم متشکرم به نظرتون حل میشه یا خیلی کار داره چون من به js تسلط ندارم که بخوام بررسی کنم

<p dir=rtl>
بعد از به وجود اومدن این مشکل در جنگو ۲ چند بار برای حل این مشکل تلاش شد ولی راه حلی پیدا نکردم (من هم روی js خیلی تسلط ندارم) در نهایت فکر میکنم که باید از یک datepicker دیگر برای این موضوع استفاده کنیم. که البته این نیز در تنظیمات پروژه قابل اعمال است.
</p>
<p dir=rtl>
به نظرم باید یک زمان خوبی روی این مشکل گذاشته شود تا بتوان آن را حل کرد.
</p>

**Comment by nimasalemahim** [comment]
این موضوع به نتیجه ای نرسید مشکل باگ مشخص شده ؟

**Comment by mehrabcz** [comment]
منم این مشکل رو خوردم و بررسی و فیکس کردم باگ رو

`$(document).ready(function () {
  $('.add-row').click(function () {
    let JQ = jQuery || {};
    if (typeof django !== "undefined") {
      JQ = django.jQuery;
    }
    // set delay to verify thats the new route was successfully created
    setTimeout(function(){
     JQ(".jalali_date-date").datepicker({
       dateFormat: "yy-mm-dd",
       changeMonth: !0,
       changeYear: !0,
     });
   }, 200)
})
})`

مرج ریکویست اکسپت میشه فیکسش کنم روی ریپو ؟

**Comment by a-roomana** [comment]
خیلی هم عالی، اگر روی جنگو ورژن ۲ و ۳ همزمان کار کنه، حتما مرج میشه.

**Comment by realxoman** [comment]
این مشکل حل نشد ؟

**Comment by mehrabcz** [comment]
> 
> 
> این مشکل حل نشد ؟

یکم من درگیر بودم وقت نکردم فردا شب حتما انجام میدم و مرج ریکویست میدم
@a-roomana

**Comment by a-roomana** [comment]
<p dir="rtl">
خیلی ممنون از زمانی که گذاشتید، واقعا ارزشمنده.

@mehrabcz 
</p>

<p dir="rtl">
من جمعه حتما بررسی و در صورتی که روی جنگو ۲ و ۳ مشکلی نداشته باشه مرج و نسخه جدید رو ریلیز میکنم.
</p>

**Comment by IKermani** [comment]
salam

in issue hamchenan baraye man vojod dare.

Django==3.2.4
Python 3.8.10

```python
class FuelTypePricePerContractInline(StackedInlineJalaliMixin, admin.StackedInline):
    model = FuelTypePricePerContract
    extra = 1
```

ono radifi ke male extra hastesh okaye vali age ye done dg bekhaym add konim, widget datepicker baz mishe vali ba click kardan rooye tarikhe made nazar, too field emal nemishe (khali mimone). cache ham pak kardam vali baz in moshkel vojod dasht. console e browser ham check kardam ke bebinam ke aya error e js yi hast ya na ke hich error yi vojod nadasht.

**Comment by mavenium** [comment]
منم این مشکل رو دارم، بعد کلیک فیلد اینلاین جاری خالی میمونه و ولیو تو اینلاین بعدی قرار میگیره.
