### ISSUE TITLE
ModelAdminJalaliMixin does not working in Django 3.0.2 

### ISSUE THREAD

**Issue by beheshtraya** [a-roomana/django-jalali-date#28]
<p dir="rtl">
سلام
</p>
<p dir="rtl">
من قبلا با جنگو نسخه ۲.۱ این مشکل رو نداشتم ولی بعد از به روزرسانی به نسخه ۳ این مشکل به وجود اومده.
</p>
<p dir="rtl">
با توجه به خروجی کنسول مرورگر فک میکنم مشکل از نسخه
jQuery 
باشه
</p>

<p dir="rtl">
،علاوه بر این که برای فیلدهای تاریخ تقویم نشون داده نمیشه  
فیلدهای 
auto complete 
هم از کار میفته و دیگه امکان انتخاب گزینه ها وجود نداره.
</p>

**Comment by a-roomana** [comment]
<p dir="rtl">سلام</p>
<p dir="rtl">بله همانطور که در یک
<a href="https://github.com/a-roomana/django-jalali-date/issues/27">ایشوی دیگر</a>
گفته شده، در تغییراتی جاواسکریپتی که در جنگو ۳ ایجاد شده که باعث این اشکال شده. امیدوار هستیم که بتونیم سریع تر این موضوع رو حل کنیم
</p>

**Comment by a-roomana** [comment]
@beheshtraya 
<p dir="rtl">با سلام در نسخه جدید (نسخه 0.3.1) مشکل یاد شد در جنگو ۳ حل شد.</p>

**Comment by beheshtraya** [comment]
ممنون از این ماژول کاربردی و همین طور پشتیانی بسیار خوب

**Comment by beheshtraya** [comment]
ممنون از پیگیری ولی همچنان همون مشکل وجود داره

حالت اول وقتی از این ماژول استفاده نشه
`class ModelNameAdmin(ModelAdminJalaliMixin, admin.ModelAdmin): ...`

امکان انتخاب هیچ گزینه ای وجود نداره
این فیلد توی ادمین به عنوان فیلد خودکار تعریف شده
![Screenshot from 2020-02-07 17-10-21](https://user-images.githubusercontent.com/2530386/74069638-dab9ff00-49cc-11ea-9ac5-51a7d70e8157.png)

تاریخ ها تبدیل میشه ولی تقویم نشون داده نمیشه
![Screenshot from 2020-02-07 17-13-37](https://user-images.githubusercontent.com/2530386/74069806-456b3a80-49cd-11ea-89e1-5e62e95e4181.png)

این هم خروجی کنسول مرورگر که تابع
datepicker 
 رو نمیشناسه

![Screenshot from 2020-02-07 17-15-20](https://user-images.githubusercontent.com/2530386/74069882-7481ac00-49cd-11ea-820c-a2f021ac0110.png)


حالتی که این ماژول استفاده نشه
`class CouponAdmin(admin.ModelAdmin): ...`

فیلد خودکار درست کار میکنه و امکان سرچ و انتخاب هم وجود داره
![Screenshot from 2020-02-07 17-17-49](https://user-images.githubusercontent.com/2530386/74070058-e78b2280-49cd-11ea-96ce-984f3970d4fa.png)

تقویم هم بارگذاری میشه که البته میلادیه
![Screenshot from 2020-02-07 17-20-09](https://user-images.githubusercontent.com/2530386/74070132-320c9f00-49ce-11ea-80be-6641faf0232d.png)

**Comment by a-roomana** [comment]
فکر میکنم که کش شده، لطفا چند بار
Ctrl + F5
بگیرید
