### ISSUE TITLE
نمایش ویجت انتخاب ساعت

### ISSUE THREAD

**Issue by MohammadGoodarzi** [a-roomana/django-jalali-date#29]
سلام
در حالت تفکیک شده تاریخ و ساعت در استفاده در فرم، ویجتی برای انتخاب ساعت دیده نمیشه در تصاویر سمپل 
 هم موردی ندیدم آیا امکان مشاهده زمان(ساعت) مانند پنل ادمین دیفالت جنگو در این ویجت شما وجود نداره؟
و اینکه در زمان اختصاص attr در حالت تفکیک شده زمان و تاریخ هر دوی فیلد های زمان و تاریخ ویجت تقویم را نمایش میدهند.

**Comment by a-roomana** [comment]
در پنل پیش فرض جنگو، ویجت مربوط به زمان کلا ۳ یا ۴ زمان ثابت را نمایش میدهد. به همین خاطر درگیر این موضوع نشدیم از ویجت پیشفرض استفاده نکردیم.
