### ISSUE TITLE
jalali fullcalender

### ISSUE THREAD

**Issue by MohammadGoodarzi** [a-roomana/django-jalali-date#31]
سلام 
تقویم جلالی چی پیشنهاد میدین؟ (fullcalender)

**Comment by a-roomana** [comment]
<p dir=rtl>
سلام
</p>

<p dir=rtl>
من ۲ حالت رو در نظر میگیرم یکی حالت تمپلیت جنگو است و یکی هم لایبرری های مثل ری‌اکت و ...
</p>

<p dir=rtl>
طبیعتا در ری‌اکت و ... من فرض میکنم که شما از این لایبرری فقط در قسمت api خود برای تبدیل تاریخ استفاده خواهید کرد.
</p>

<p dir=rtl>
البته برای ری‌اکت من نمیدونم چه تعداد لایبرری تاریخ شمسی و با چه کیفیتی وجود دارد اما یه دونه سراغ دارم اما از کیفیتش اطلاع ندارم
</p>

[BB Calender](https://github.com/bimebazar/BB-Calendar)

<p dir=rtl>
اما برای تمپلیت جنگو از Jquery Ui استفاده میکنیم. همان تقویمی که در این لایبرری  Django Jalali Date از اون استفاده شده است. هرچند که این لایبرری واقعا قدیمی شده است.
</p>

<p dir=rtl>
برای اطلاع عرض میکنیم که شما میتوانید مطابق با تنظیمات Datepicker دل خواه خود را به جای تقویم موجود جایگزین کنید و هیچ محدودیتی در این قسمت وجود ندارد. تنها باید فرمت تاریخ مثل 
<code dir=ltr>1399-01-28</code>
 باشد. و اعداد آن انگلیسی باشند.
</p>
