### ISSUE TITLE
نمایش تقویم فارسی در django admin

### ISSUE THREAD

**Issue by john685** [a-roomana/django-jalali-date#33]
سلام...ممنون از اینکه همچین ماژول کاربردی رو نوشتین...
میخواستم بپرسم اگه بخواییم فیلد های تاریخ مدل ها رو شمسی کنیم جوری که تووی پنل
admin
بتونیم تاریخ ها رو شمسی نشون بدیم...چجوریه؟
یعنی فیلدهای 
Model
چه تغییراتی لازم دارن که بشه اون ها رو شمسی کرد؟

**Comment by a-roomana** [comment]
سلام با استفاده از این لایبرری نیازی به تغییر در سطح مدل بیا دیتابیس نیست.

تنها کاری که باید با توجه به داکیومنت در کلاس ادمین مدل خود
ModelAdminJalaliMixin
 را به ارث ببرید.
