### ISSUE TITLE
خطا بعد از اضافه نمودن جلالی به جنگو

### ISSUE THREAD

**Issue by EhsanSafir** [a-roomana/django-jalali-date#35]
سلام بعد اینکه لایبرری اد می کنم جنگو این پیامو نشون میده
`File "/home/safir/.virtualenvs/deply-env/lib/python3.6/site-packages/jalali_date/admin.py", line 6, in <module>
    from jalali_date import widgets as j_widgets
  File "/home/safir/.virtualenvs/deply-env/lib/python3.6/site-packages/jalali_date/widgets.py", line 4, in <module>
    from django.contrib.admin.templatetags.admin_static import static
ModuleNotFoundError: No module named 'django.contrib.admin.templatetags.admin_static'`

**Comment by a-roomana** [comment]
@EhsanSafir 

لطفا نسخه جنگو خود را اعلام کنید.
