### ISSUE TITLE
can not import from jalalidate

### ISSUE THREAD

**Issue by jamalhosseini** [a-roomana/django-jalali-date#40]
Hi,
When i want import jalali-date in view , raised erorr : `Unresolved reference 'jalali_date'.`

I installed all dependensies:

> pip3 install django-jalali-date-3
> pip3 install django-jalali-date

and **jdatetime** and **pytz** module.

also in project settings added **'jalali-date'** to installed apps.

- python version : 3.8
- django version : 2.1

**Comment by jamalhosseini** [comment]
Problem was pycharm app.
I used VSCode and using module.

**Comment by a-roomana** [comment]
> Problem was pycharm app.
> I used VSCode and using module.

please check settings and environments of Pycharm. I already use Pycharm.

**Comment by jamalhosseini** [comment]
> > Problem was pycharm app.
> > I used VSCode and using module.
> 
> please check settings and environments of Pycharm. I already use Pycharm.

**Comment by jamalhosseini** [comment]
Thank you for replay,
I have a question too, How to using out of Admin panel?

**Comment by a-roomana** [comment]
Please refer to the document. There are proverbs of views, forms and templates
