### ISSUE TITLE
str method

### ISSUE THREAD

**Issue by vahidodin** [a-roomana/django-jalali-date#47]
سلام . من یک مدل دارم که یک فیلدش جی دیت فیلد هست . در یک مدل دیگه فارن کی زدم به این مدل . ولی وقتی میخوام تو پنل ادمین مدل دوم رو  نمایش بده با توجه به اینکه حتی متد اس تی ار مدل اول رو قرار دادم رو اون فیلد ولی تو مدل دوم خالی نمایش نمیده . باید چیکار کنم ؟‌ 

[https://pasteboard.co/Khc2iR3.png](url)
[https://pasteboard.co/Khc2Qob.png](url)

**Comment by a-roomana** [comment]
<p dir=rtl>
میتونید مشابه داکیومنت یک متد در کلاس ادمین تون ایجاد کنید و با استفاده از strftime به فرمت دلخواه تاریخ رو نمایش بدهید.
</p>
