### ISSUE TITLE
تاریخ شمسی در serializer 

### ISSUE THREAD

**Issue by sardarmz** [a-roomana/django-jalali-date#58]
سلام برای تبدیل تاریخ به شمسی تو قسمت serializer چطوری میشه از این پکیج استفاده کرد خیلی گشتم مثال فقط برای پنل ادمین هست برای api پیدا نکردم

**Comment by a-roomana** [comment]
hi

you can use `datetime2jalali` or `date2jalali`.

sample of using these functions exists on readme.md (section admin.py)
