### ISSUE TITLE
اشکال در ثبت تاریخ

### ISSUE THREAD

**Issue by arashghalami** [a-roomana/django-jalali-date#6]
سلام
وقتی تاریخ را ثبت می کنم آنرا به صورت میلادی فرض می کند و وقتی دوباره بازش می کنم دوباره آنرا شمسی می کند
 مثلا 1396 را که ثبت می کنی به جای اینکه آنرا به تاریخ میلادی معادلش مثلا 2018 ذخیره کند همان 1396 را ذخیره می کند 
بعد که دوباره وارد رکورد می شوی عدد 1396 را به شمسی بر می کرداند و 775 نشان می دهد
در همین حالت هم که ذخیره را می زنی اعلام می کند تاریخ نامعتبر وارد شده است
ورژن جنگو 1.11 و پایتون 3.6.3

**Comment by a-roomana** [comment]
سلام، فرض من بر این است که تاریخی که از کاربر میگیرم شمسی است، و بعد از تبدیل به میلادی در دیتابیس ذخیره میشود. هنگام نمایش آن تاریخ به صورت  میلادی از دیتابیس خوانده میشود و بعد از تبدیل به شمسی نمایش داده میشود.
 لطفا به کد های نمونه بیشتر توجه کنید، اگر هم فکر میکنید کدتون کاملا درست است کدتون روبرای من ارسال کنید، تا حالت خاص مشکل درلایببری را متوجه بشم.
ممنون

**Comment by FarimanGhaedi** [comment]
با سلام. من هم مشکل مشابهی دارم
من یک مدل برای ذخیره مشخصات افراد دارم که یکی از فیلدهاش تاریخ تولد هست
زمانی که به بخش ادمین سایت وارد میشم و لیست یوزرها رو نگاه میکنم اون فیلد رو به صورت میلادی نشون میده اما وقتی که روی یک یوزر کلیک میکنم که مشخصاتش رو ویرایش کنم تاریخ به صورت شمسی نشون داده میشه.
در فایل مدل برای فیلد روز تولد از
default='1385-06-15"
استفاده کردم که مطمئن باشم داده اولیه به صورت شمسی هست ولی همچنان مشکل برقراره
در ضمن در قسمت ادمین برای مدل ادمین
ModelAdminJalaliMixin
رو ایمپورت کردم
ممنون میشم راهنمایی کنید
