### ISSUE TITLE
@a-roomana

### ISSUE THREAD

**Issue by iam-Robo** [a-roomana/django-jalali-date#62]
@a-roomana
<p dir="rtl">
سلام، ضمن تشکر از زحمات شما  من از جنگو  3 استفاده میکنم، هر کاری کردم ایام هفته ماه ها فارسی بشن، نشد، همه ی این روش ها رو تست کردم.
ممنون میشم راه حلی ارائه بدین
</p>

_Originally posted by @vhdm in https://github.com/a-roomana/django-jalali-date/issues/20#issuecomment-574375315_

**Comment by iam-Robo** [comment]
سلام 
منم همین مشکل رو دارم با تنظمیات environment مورد حل نشد، ممنون میشم کمکم کنید.

**Comment by a-roomana** [comment]
https://github.com/a-roomana/django-jalali-date/issues/60 duplicates this issue
