### ISSUE TITLE
عدم نمایش ساهای گذشته در کمبوباکس

### ISSUE THREAD

**Issue by afmghasemi** [a-roomana/django-jalali-date#63]
سلام و وقت بخیر
توی جانگو ادمین تقویم جایگزین شده ولی در کمبو باکس مربوط به سال تا 10 سال قبل را نمایش میده و راهی وجود نداره مثلا سال 1350 را انتخاب کنیم این مورد قابل تنظیم و تغییر هست ؟

**Comment by AmirMahmood** [comment]
سلام.
ساده ترین راه حل تایپ کردن سال مورد نطرتون هست.
ولی اگه کمبوباکس براتون مهم هست، با این روش که به نوعی یک جور حقه هست میشه به سال های قبل تر یا بعد تر رسید: کمبوباکس مربوط به سال هر بار که باز میشه 10 سال قبل و بعد مقدار فعلی کمبوباکس رو نشون میده. شما اگه سال دیگری رو انتخاب کنید و مجددا کمبوباکس رو باز کنید، اینبار 10 سال قبل و بعد نسبت به سالی که انتخاب کردید نمایش داده میشه.

**Comment by afmghasemi** [comment]
سلام 
خیلی ممنون بابت توضیحات
