### ISSUE TITLE
add document for DRF

### ISSUE THREAD

**Issue by iam-benyamin** [a-roomana/django-jalali-date#66]
Added documentation for using the Django Rest Framework internal library

**Comment by a-roomana** [comment]
if you want to show the Jalali date on JSON response then you should use `datetime2jalali`. you can see some examples of using it in the documentation.

if you want to receive the Jalali date on Json request then you should  parse the input and use [jDatetime](https://pypi.org/project/jdatetime/) as a dependency of django-jalali-date

if you have any question/suggestion please tell me.
