### ISSUE TITLE
Fieldsets styles issue with Django 4.2

### ISSUE THREAD

**Issue by aminvsf** [a-roomana/django-jalali-date#67]
After upgrading from Django 4.1.7 to Django 4.2, some fieldsets styles in Django admin panel aren't working as expected.

Here's a part of the admin model's code:
![Screenshot from 2023-04-13 12-29-31](https://user-images.githubusercontent.com/75808738/231710344-9045b601-7106-40b0-a07b-7396605eb1ea.png)

So our desired output is that the specified fields must be placed in the same line. But when we use 'ModelAdminJalaliMixin' in our admin model, it brakes those styles.
![Screenshot from 2023-04-13 12-29-09](https://user-images.githubusercontent.com/75808738/231711006-aaaabbac-9284-40b7-9aef-e3230ea9a413.png)

**Comment by a-roomana** [comment]
I solved the problem in this [merge request](https://github.com/a-roomana/django-jalali-date/pull/68). I will publish the new version next Friday, God willing.

**Comment by a-roomana** [comment]
the new version (1.0.2) is published.

@aminvsf

**Comment by aminvsf** [comment]
Great, thanks!
