### ISSUE TITLE
مشکل در هنگام readonly شدن فیلد‌ٰها در ادمین

### ISSUE THREAD

**Issue by ijami** [a-roomana/django-jalali-date#8]
سلام

ضمن تشکر بابت کتاب‌خانه‌ای که آماده کرده‌اید، زمانی که هنگان نمایش تاریخ در ادمین فیلد حاوی تاریخ 
readonly
باشد باعث می‌شود بقیه فیلد‌ٰها درست نمایش داده نشوند و در 
TabularInline
هم اصلا تبدیل به تاریخ شمسی صورت نمی‌گیرد در صورتی که 
readonly
باشد.

**Comment by ijami** [comment]
سلام مجدد

بسیار ممنون

من دیدم که کامیت جدید کرده بودین. میخواستم بپرسم آیا پکیج
pip 
رو هم به روز کرده‌اید؟

**Comment by a-roomana** [comment]
خیلی ممنون از پیگیریتون. امیدوارم این پکیج برای شما مفید باشه و اگر هر بازخوردی دارید خوشحال میشم بگید.
بله نسخه جدید منتشر شد.

**Comment by ijami** [comment]
سلام

ضمن تشکر از آپدیت.
می‌خواستم اطلاع بدم من آپدیت کردم پکیج رو اما به نظر می‌رسه همچنان مشکل
باقیست و مشکلات جدیدی هم اضافه شد. از جمله این که قبلا فیلدی که به صورت
تابع در ادمین اضافه میشد (مثل لاین نامبر برای اینلاین مدل‌ها) الان دیگر کار
نمی‌کند.

با احترام
جامی مقدم

**Comment by a-roomana** [comment]
![screenshot from 2018-04-24 00-25-14](https://user-images.githubusercontent.com/13819361/39150079-68034a4a-4756-11e8-9248-6393838729cf.png)

بعد از صحبت شما من دوباره تست گرفتم، و مطابق عکس بالا همه چیز درست بود. اگه فکر میکنید واقعا مشکلی هست بیشتر توضیح بدهید.

**Comment by ijami** [comment]
سلام

ببخشید مقدار زیادی درگیر بودم روزهای اخیر چون میخواستم با تصویر و مفصل جواب
بدم دیر شد. البته الان هم هنوز درگیر هستم و مفصل نمیتونم توضیح بدم با پیوست
کد که عذر میخوام.

در حال حاضر به نظر میرسه چند مشکل وجود دارد
مشکل اصلی هنگامی است که در ادمین برخی فیلد ها read only می شوند که در این
صورت این فیلدها چه در ادمین عادی چه در تیبیولار درست نمایش داده نمیشوند.
پس از تغییر در صورتی که فیلدی با تابع درون ادمین تعریف شود و درون فیلدز
اضافه شود (مثل اضافه کردن شماره خط به فیلدهای تیبیولار) آن فیلدها شناخته
نمی‌شوند.

فردا امتحانی دارم که بعد از اون سرم خلوت میشه و اگر این توضیحات کفایت
نمی‌کرد مفصل تر عرض میکنم خدمتتون.

با تشکر

**Comment by ijami** [comment]
سلام

بسیار عالی. دست شما درد نکنه بله مشکل برطرف شد و عملکرد مطلوب را دارد.
خیلی ممنون از زحماتتون.



2018-04-27 20:54 GMT+04:30 Arman Roomana <notifications@github.com>:
