### ISSUE TITLE
Incompatibility with Django=5.0.4

### ISSUE THREAD

**Issue by mehdi-ebrahimi** [a-roomana/django-jalali-date#82]
Persian calendar widget does not work on Django version 5.0.4 .
I tried hard to figure out why it wasn't working until I changed the Django version to 4.2.6 and it was fixed.
best regards,

**Comment by a-roomana** [comment]
I'll wait until Friday to add if any other changes are needed.


you can install and your changes by bellow command:

```base
pip install https://github.com/aminvsf/django-jalali-date.git@master
```
